language: python

python:
    # - 2.7
    - 3.5
    - 3.6

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of packages
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

# addons:
#     apt:
#         packages:
#             - graphviz
#             - texlive-latex-extra
#             - dvipng

env:
    global:

        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test'
        - PIP_DEPENDENCIES='git+https://github.com/adrn/thejoker'

        # For this package-template, we include examples of Cython modules,
        # so Cython is required for testing. If your package does not include
        # Cython code, you can set CONDA_DEPENDENCIES=''
        - CONDA_DEPENDENCIES='pyyaml sqlalchemy h5py'
        - CONDA_CHANNELS='astropy-ci-extras astropy'

        - BUILD_PAPER='false'

    matrix:
        # Make sure that egg_info works without dependencies
        - SETUP_CMD='egg_info'
        # Try all python versions with the latest numpy
        - SETUP_CMD='test'

matrix:

    # Don't wait for allowed failures
    # fast_finish: true

    include:

        # compile the latex to make a PDF of the paper
        # - os: linux
        #   env: BUILD_PAPER='true'
        #   python: 3.5

        # Do a coverage test in Python 2.
        # - python: 2.7
        #   env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        # - python: 2.7
        #   env: SETUP_CMD='build_sphinx -w'

        # - python: 2.7
        #   env: ASTROPY_VERSION=lts
        # - python: 3.5
        #   env: ASTROPY_VERSION=lts

        # Do a PEP8 test with pycodestyle
        # - python: 3.5
        #   env: MAIN_CMD='pycodestyle packagename --count' SETUP_CMD=''

    # allow_failures:
    #     # Do a PEP8 test with pycodestyle
    #     # (allow to fail unless your code completely compliant)
    #     - python: 3.5
    #       env: MAIN_CMD='pycodestyle packagename --count' SETUP_CMD=''

install:
    - source ci/install.sh

before_script:
    - source ci/before_script.sh

script:
    - source ci/script.sh

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    # - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='packagename/tests/coveragerc'; fi
