name: twoface

channels:
  - astropy

dependencies:
  - python=3
  - astropy
  - numpy
  - matplotlib
  - sqlalchemy
  - pyyaml
  - h5py
  - pip
  - pip:
    - emcee
    - corner
    - git+https://github.com/adrn/thejoker
    - git+https://github.com/adrn/schwimmbad

