name: twoface

channels:
  - astropy

dependencies:
  - python=3
  - astropy
  - numpy
  - cython
  - matplotlib
  - scipy
  - h5py
  - sqlalchemy
  - pyyaml
  - pip
  - pip:
    - emcee
    - corner
    # - git+https://github.com/adrn/thejoker

