name: twoface-new

channels:
  - astropy

dependencies:
  - python=3
  - astropy
  - numpy
  - scipy
  - matplotlib
  - sqlalchemy
  - pyyaml
  - cython
  - h5py
  - jupyter
  - pip
  - pip:
    - emcee
    - corner
    - tqdm
    - git+https://github.com/adrn/twobody
    - git+https://github.com/adrn/thejoker@twobody-0.1
    - git+https://github.com/adrn/schwimmbad
