/* psql -u adrian < create_db.sql */

drop database if exists apogee;
create database apogee;

\connect apogee

DROP TABLE IF EXISTS allvisit;
CREATE TABLE allvisit (
    id SERIAL primary key,
    VISIT_ID text,
    TARGET_ID text,
    APRED_VERSION text,
    APOGEE_ID text,
    FILE text,
    FIBERID smallint,
    PLATE smallint,
    MJD integer,
    LOCATION_ID smallint,
    RA double precision,
    DEC double precision,
    GLON double precision,
    GLAT double precision,
    J real,
    J_ERR real,
    H real,
    H_ERR real,
    K real,
    K_ERR real,
    AK_TARG real,
    AK_TARG_METHOD text,
    AK_WISE real,
    SFD_EBV real,
    RA_TARG double precision,
    DEC_TARG double precision,
    APOGEE_TARGET1 integer,
    APOGEE_TARGET2 integer,
    TARGFLAGS text,
    SNR real,
    STARFLAG integer,
    STARFLAGS text,
    DATEOBS text,
    JD double precision,
    BC real,
    VTYPE smallint,
    VREL real,
    VRELERR real,
    VHELIO real,
    VLSR real,
    VGSR real,
    CHISQ real,
    RV_TEFF real,
    RV_FEH real,
    RV_LOGG real,
    RV_ALPHA real,
    RV_CARB real,
    SYNTHFILE text,
    ESTVTYPE smallint,
    ESTVREL real,
    ESTVRELERR real,
    ESTVHELIO real,
    SYNTHVREL real,
    SYNTHVRELERR real,
    SYNTHVHELIO real,
    FIELD text,
    COMMISS smallint,
    WASH_M real,
    WASH_M_ERR real,
    WASH_T2 real,
    WASH_T2_ERR real,
    DDO51 real,
    DDO51_ERR real,
    IRAC_3_6 real,
    IRAC_3_6_ERR real,
    MAG_4_5 real,
    MAG_4_5_ERR real,
    IRAC_5_8 real,
    IRAC_5_8_ERR real,
    IRAC_8_0 real,
    IRAC_8_0_ERR real,
    WISE_4_5 real,
    WISE_4_5_ERR real,
    GIANT smallint,
    STAR smallint,
    PMRA real,
    PMDEC real,
    PMCAT text
);


/*
    We could set up a foreign key constraint between the two tables, but I'm lazy.
    Also, I don't really need this table so for now I ignore...
*/
-- DROP TABLE IF EXISTS allstar;
-- CREATE TABLE allstar (
--     id SERIAL primary key,
--     APSTAR_ID text,
--     TARGET_ID text,
--     ASPCAP_ID text,
--     FILE text,
--     APOGEE_ID text,
--     TELESCOPE text,
--     LOCATION_ID smallint,
--     FIELD text,
--     J real,
--     J_ERR real,
--     H real,
--     H_ERR real,
--     K real,
--     K_ERR real,
--     RA double precision,
--     DEC double precision,
--     GLON double precision,
--     GLAT double precision,
--     APOGEE_TARGET1 integer,
--     APOGEE_TARGET2 integer,
--     APOGEE_TARGET3 integer,
--     TARGFLAGS text,
--     NVISITS integer,
--     COMMISS smallint,
--     SNR real,
--     STARFLAG integer,
--     STARFLAGS text,
--     ANDFLAG integer,
--     ANDFLAGS text,
--     VHELIO_AVG real,
--     VSCATTER real,
--     VERR real,
--     VERR_MED real,
--     SYNTHVHELIO_AVG real,
--     SYNTHVSCATTER real,
--     SYNTHVERR real,
--     SYNTHVERR_MED real,
--     RV_TEFF real,
--     RV_LOGG real,
--     RV_FEH real,
--     RV_ALPHA real,
--     RV_CARB real,
--     RV_CCFWHM real,
--     RV_AUTOFWHM real,
--     SYNTHSCATTER real,
--     STABLERV_CHI2 real[],
--     STABLERV_RCHI2 real[],
--     CHI2_THRESHOLD real[],
--     STABLERV_CHI2_PROB real[],
--     MEANFIB real,
--     SIGFIB real,
--     SNREV real,
--     APSTAR_VERSION text,
--     ASPCAP_VERSION text,
--     RESULTS_VERSION text,
--     EXTRATARG integer,
--     MIN_H text,
--     MAX_H text,
--     MIN_JK text,
--     PARAM real[],
--     FPARAM real[],
--     PARAM_COV real[],
--     FPARAM_COV real[],
--     TEFF real,
--     TEFF_ERR real,
--     LOGG real,
--     LOGG_ERR real,
--     VMICRO real,
--     VMACRO real,
--     VSINI real,
--     M_H real,
--     M_H_ERR real,
--     ALPHA_M real,
--     ALPHA_M_ERR real,
--     ASPCAP_CHI2 real,
--     ASPCAP_CLASS text,
--     ASPCAPFLAG integer,
--     ASPCAPFLAGS text,
--     PARAMFLAG integer[],
--     FELEM real[],
--     FELEM_ERR real[],
--     X_H real[],
--     X_H_ERR real[],
--     X_M real[],
--     X_M_ERR real[],
--     C_FE real,
--     CI_FE real,
--     N_FE real,
--     O_FE real,
--     NA_FE real,
--     MG_FE real,
--     AL_FE real,
--     SI_FE real,
--     P_FE real,
--     S_FE real,
--     K_FE real,
--     CA_FE real,
--     TI_FE real,
--     TIII_FE real,
--     V_FE real,
--     CR_FE real,
--     MN_FE real,
--     FE_H real,
--     CO_FE real,
--     NI_FE real,
--     CU_FE real,
--     GE_FE real,
--     RB_FE real,
--     Y_FE real,
--     ND_FE real,
--     C_FE_ERR real,
--     CI_FE_ERR real,
--     N_FE_ERR real,
--     O_FE_ERR real,
--     NA_FE_ERR real,
--     MG_FE_ERR real,
--     AL_FE_ERR real,
--     SI_FE_ERR real,
--     P_FE_ERR real,
--     S_FE_ERR real,
--     K_FE_ERR real,
--     CA_FE_ERR real,
--     TI_FE_ERR real,
--     TIII_FE_ERR real,
--     V_FE_ERR real,
--     CR_FE_ERR real,
--     MN_FE_ERR real,
--     FE_H_ERR real,
--     CO_FE_ERR real,
--     NI_FE_ERR real,
--     CU_FE_ERR real,
--     GE_FE_ERR real,
--     RB_FE_ERR real,
--     Y_FE_ERR real,
--     ND_FE_ERR real,
--     C_FE_FLAG real,
--     CI_FE_FLAG real,
--     N_FE_FLAG real,
--     O_FE_FLAG real,
--     NA_FE_FLAG real,
--     MG_FE_FLAG real,
--     AL_FE_FLAG real,
--     SI_FE_FLAG real,
--     P_FE_FLAG real,
--     S_FE_FLAG real,
--     K_FE_FLAG real,
--     CA_FE_FLAG real,
--     TI_FE_FLAG real,
--     TIII_FE_FLAG real,
--     V_FE_FLAG real,
--     CR_FE_FLAG real,
--     MN_FE_FLAG real,
--     FE_H_FLAG real,
--     CO_FE_FLAG real,
--     NI_FE_FLAG real,
--     CU_FE_FLAG real,
--     GE_FE_FLAG real,
--     RB_FE_FLAG real,
--     Y_FE_FLAG real,
--     ND_FE_FLAG real,
--     ELEM_CHI2 real[],
--     ELEMFLAG integer[],
--     REDUCTION_ID text,
--     SRC_H text,
--     WASH_M real,
--     WASH_M_ERR real,
--     WASH_T2 real,
--     WASH_T2_ERR real,
--     DDO51 real,
--     DDO51_ERR real,
--     IRAC_3_6 real,
--     IRAC_3_6_ERR real,
--     IRAC_4_5 real,
--     IRAC_4_5_ERR real,
--     IRAC_5_8 real,
--     IRAC_5_8_ERR real,
--     IRAC_8_0 real,
--     IRAC_8_0_ERR real,
--     WISE_4_5 real,
--     WISE_4_5_ERR real,
--     TARG_4_5 real,
--     TARG_4_5_ERR real,
--     AK_TARG real,
--     AK_TARG_METHOD text,
--     AK_WISE real,
--     SFD_EBV real,
--     WASH_DDO51_GIANT_FLAG smallint,
--     WASH_DDO51_STAR_FLAG smallint,
--     PMRA real,
--     PMDEC real,
--     PM_SRC text,
--     VISITS text,
--     ALL_VISITS text,
--     VISIT_PK integer[],
--     ALL_VISIT_PK integer[],
--     FPARAM_CLASS double precision[][],
--     CHI2_CLASS double precision[][]
-- );
